-- AlterTable
ALTER TABLE "TradeConfig" ADD COLUMN     "intervalMinutes" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "maPeriodA" INTEGER NOT NULL DEFAULT 21,
ADD COLUMN     "maPeriodB" INTEGER NOT NULL DEFAULT 21,
ADD COLUMN     "rsiEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "rsiPeriod" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN     "scheduleMode" TEXT NOT NULL DEFAULT 'window',
ADD COLUMN     "timeframeA" TEXT NOT NULL DEFAULT '30m',
ADD COLUMN     "timeframeB" TEXT NOT NULL DEFAULT '4h';
